spring.application.name=online-etkinlik

# Gizli şifre dosyasını içeri aktarır
spring.config.import=optional:classpath:application-secret.properties

spring.datasource.url=jdbc:mysql://localhost:3306/online_etkinlik?serverTimezone=UTC&characterEncoding=UTF-8
# Username ve password burada yok, secret dosyasından okunacak!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Iyzico Sandbox Ayarları
iyzico.base.url=https://sandbox-api.iyzipay.com
# Api key ve secret key burada yok, secret dosyasından okunacak!

# Oturum Zaman Aşımı
server.servlet.session.timeout=30m