spring.application.name=online-etkinlik

spring.datasource.url=jdbc:mysql://localhost:3306/online_etkinlik?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Iyzico Sandbox Ayarları
iyzico.api.key=
iyzico.secret.key=
iyzico.base.url=https://sandbox-api.iyzipay.com
